apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-11-24T11:07:19Z"
  generation: 10
  name: start
  namespace: argo-cd
  resourceVersion: "3957"
  uid: d2a53629-f718-4663-b2e1-f9b1d2ce3572
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./start-apps
    repoURL: "{{ .Values.argocd.repo }}"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
