apiVersion: v1
data:
  password: {{ .Values.argocd.token | b64enc }}
  project: ZGVmYXVsdA==
  type: Z2l0
  url: {{ .Values.argocd.repo | b64enc }}
  username: amVubmVybWFuZA==
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  creationTimestamp: "2024-11-24T10:02:12Z"
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-secrets-ding
  namespace: argo-cd
  resourceVersion: "1318"
  uid: b66454c6-5399-4122-aa50-1e2c676f3d06
type: Opaque