{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-secrets-{{ .name }}
  namespace: argo-cd
type: Opaque
data:
  password: {{ .token | b64enc }}
  project: ZGVmYXVsdA==
  type: Z2l0
  url: {{ .repo | b64enc }}
  username: amVubmVybWFuZA==
---
{{- end }}