apiVersion: apps/v1
kind: Deployment
metadata:
  name: start-apps
  namespace: argo-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: start-apps
  template:
    metadata:
      labels:
        app: start-apps
    spec:
      containers:
       - env:
        - name: REPO_URL
          valueFrom:
            configMapKeyRef:
              name: repo-config
              key: repo