apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 04-apps-applications-set
  namespace: argocd
spec: 
  generators:
  - git:
      repoURL: https://github.com/jennermand/kind
      revision: main
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
    spec: 
      project: default      
      source:
        repoURL: https://github.com/jennermand/kind
        targetRevision: main
        path: '{{`{{path}}`}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{path.basename}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true 