apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: start-apps
  namespace: argo-cd
spec:
  generators:
    - env:
        envs:
          - name: REPO_URL
            configMapRef:
              name: repo-config
              key: repo
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: '{{env.REPO_URL}}'
        targetRevision: HEAD
        path: 'apps/{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: