apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: start
  namespace: argo-cd
spec: 
  generators:
  - git:
      repoURL: {{ .Values.env.REPO_URL }} }}
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
    spec: 
      project: default      
      source:
        repoURL: {{ .Values.env.REPO_URL  }}
        targetRevision: HEAD
        path: '{{`{{path}}`}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{path.basename}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true 