apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: start-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/jennermand/kind'
        revision: HEAD
        directories:
          - path: 'apps/*'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/jennermand/kind.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true