apiVersion: v1
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJrbWRkaW1hYWNyZGV2LmF6dXJlY3IuaW8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIk0ySXpNV1ZoTnpZdE1EUXpOQzAwWlRrMkxXRTNZell0WWpsalptWXhOakprWlRFNU9qTjJXamhSZm1KbVFXMDNSMVEzUWk1S2MybGZOMUV4WmxFeU5YWjFORlZPYjBGelNrSmtZWFk9IgogICAgICAgICAgICAgICAgfQogICAgICAgIH0KfQ==
kind: Secret
metadata:
  name: image-pull-secret
  namespace: dev-jp-con
type: kubernetes.io/dockerconfigjson