{{- if .Values.argocd.event }}
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: pod-status-event-source
  namespace: argo-events
spec:
  template:
    serviceAccountName: default
  resource:
    app:      
      group: apps
      version: v1
      resource: deployments
      eventTypes:
        - ADD
        - UPDATE
        - DELETE
      filter:
        afterStart: true
{{- end }}