init:
  token: token-goes-here

events:
  argocd:
    token: "{{ .Values.argocd.token }}"
    event: &events choice-here

  password:
    secretName: github-token
    secretKey: token

  namespace: argo-events

argocd:
  argocd:
    repo: "https://github.com/sparnord/jensk-dev"
    event: events

  token: your-token-here-global
  repositories:
  - repo: val
    name: val
    token: val
  argo-cd:
    dex:
      enabled: false
    notifications:
      enabled: false
    applicationSet:
      enabled: true
    ingress:
      enabled: true
    server:
      insecure: true
      ingressGrpc:
        enabled: true

    config:
      secret:
        argocdServerAdminPassword: ding

  password:
    secretName: github-token
    secretKey: token

  namespace: argo-events
