argocd:
  argocd:
    repo: "https://github.com/sparnord/jensk-dev"
    token: your-token-here

  argo-cd:
    dex:
      enabled: false
    notifications:
      enabled: false
    applicationSet:
      enabled: true
    ingress:
      enabled: true
    server:
      insecure: true
      ingressGrpc:
        enabled: true

    config:
      secret:
        argocdServerAdminPassword: ding

events:
  argocd:
    token: "{{ .Values.argocd.argocd.token }}"

  password:
    secretName: github-token
    secretKey: token

  namespace: argo-events
