events:
  argocd:
    token: "{{ .Values.argocd.argocd.token }}"
    event: &events choice-here

  password:
    secretName: github-token
    secretKey: token

  namespace: argo-events

argocd:
  argocd:
    repo: your-repo-here
    token: your-token-here
    event: *events

  argo-cd:
    dex:
      enabled: false
    notifications:
      enabled: false
    applicationSet:
      enabled: true
    ingress:
      enabled: true
    server:
      insecure: true
      ingressGrpc:
        enabled: true

    config:
      secret:
        argocdServerAdminPassword: ding


