apiVersion: v1
kind: Namespace
metadata:
  name: applications
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-jp-con
  annotations:
    argocd.argoproj.io/sync-wave: "-1"