apiVersion: v1
data:
  password: ZGZpdHNkbmtsczRtZTJmbHc2bWFvYzNoNDQ0cDNqeWUybmVhY2dpa2xoa2l4N2o2aGM1YQ==
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9rbWQtZGltYUBkZXYuYXp1cmUuY29tL2ttZC1kaW1hL0tNRC5ESU1BLkNvbm5lY3RORUMvX2dpdC9LTUQuRElNQS5Db25uZWN0TkVDLkhlbG1DaGFydHM=
  username: TkZL
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-playground-app-of-apps-secrets
  namespace: argo-cd
type: Opaque

