name: Pod Status Change

on:
  repository_dispatch:
    types: [pod_status_change]

  workflow_dispatch:
    inputs:
      full_payload:
        description: "Name of the Pod"
        required: false
      event_type:
        description: "Status of the Pod"
        required: false

jobs:
  handle-pod-status-change:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Handle Pod Status Change
        run: |
          echo "Pod Name: ${{ github.event.client_payload.pod_name }}"
          echo "Pod Status: ${{ github.event.client_payload.pod_status }}"
          echo "Job Name: ${{ inputs.event_type }}"
          echo "Full Payload: ${{ inputs.full_payload }}"
